export const CHANGE_ADJACENCY = 'CHANGE_ADJACENCY';
export const CHANGE_VERTEX_COUNT = 'CHANGE_VERTEX_COUNT';
export const SHOW_RESULT = 'SHOW_RESULT';
export const CHANGE_FIRST_ADJACENCY = 'CHANGE_FIRST_ADJACENCY';
export const CHANGE_SECOND_ADJACENCY = 'CHANGE_SECOND_ADJACENCY';
export const CHANGE_FIRST_VERTEX_COUNT = 'CHANGE_FIRST_VERTEX_COUNT';
export const CHANGE_SECOND_VERTEX_COUNT = 'CHANGE_SECOND_VERTEX_COUNT';
